### ISSUE TITLE
[Dota 2 Web API]wrong  int type in pojo object 

### ISSUE THREAD

**Issue by John-Chan** [ribasco/async-gamequery-lib#13]
# Verify

for example,the [match_Id](https://github.com/ribasco/async-gamequery-lib/blob/d9015c64dcfe9a1e696233642fbbc2efbac4facf/protocols/valve/dota2/webapi/src/main/java/com/ibasco/agql/protocols/valve/dota2/webapi/pojos/Dota2MatchHistoryInfo.java#L41) filed. This is easy to test and verify:

1. load match history 
```
https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v1?account_id=125038361&key=XXXX
```
2. from the response,we can determine match_id  is a long type ,for example
```
{
    "match_id": 3429744798,
    "match_seq_num": 2989122942,
    ...
},
{
    "match_id": 3428039636,
    "match_seq_num": 2987709399
	...
}
```

# The problem

```
int matchId= -1234;
Dota2MatchDetails details = matchInterface.getMatchDetails(matchId).get();
```
not work,getMatchDetails dont accept negative ,see [AbstractWebRequest.urlParam](https://github.com/ribasco/async-gamequery-lib/blob/d9015c64dcfe9a1e696233642fbbc2efbac4facf/core/src/main/java/com/ibasco/agql/core/AbstractWebRequest.java#L72)

```
Dota2MatchHistoryCriteria dota2MatchHistoryCriteria = new Dota2MatchHistoryCriteria();
dota2MatchHistoryCriteria.accountId(125038361L);
Dota2MatchHistory matchHistory = matchInterface.getMatchHistory(dota2MatchHistoryCriteria).get();

matchHistory.getMatches().forEach(matchHistoryInfo ->{
    if(matchHistoryInfo.getMatchId() < 0){
        System.out.println("bug");// negative 
    }
});
```

**Comment by ribasco** [comment]
Thanks for reporting the issue. The match id property should really be of `long` type and not `int` in this case.  

As for the following code you pointed at: https://github.com/ribasco/async-gamequery-lib/blob/d9015c64dcfe9a1e696233642fbbc2efbac4facf/core/src/main/java/com/ibasco/agql/core/AbstractWebRequest.java#L69-L76 this should/will be removed as it is unnecessary and redundant. 

I'll be pushing the fix on the next release soon. Thanks
