### ISSUE TITLE
To avoid data loss,if library cant determine int types exactly, let caller side handle it 

### ISSUE THREAD

**Issue by John-Chan** [ribasco/async-gamequery-lib#14]
Thanks for fix #13,but `match_id`  is not the only one need fix,i am sure `match_seq_num`(IDOTA2Match_570/GetMatchHistory) is int64 type too.
In my understanding,there is no offical doc for those data2 api,right? so we have to guess what is the right one,and test/verify them manually,i think it so hard for you to test them all,and they may changed in the future.

In my opinion,the library dont have to map data types (in fact,int types) strictly,let caller handle it,this is can be done by the follow workaround:
- avoid different data type between pojos/resquest-interfaces(e.g. account_id is long type in Dota2GamePlayer ,but int type in Dota2FantasyProPlayerInfo and Dota2Fantasy.getPlayerOfficialInfo)
- if we cant makesure the right data type,use a 'larger' type,e.g. use long for`account_id`,`last_update_time`,`time_joined` instead of int,let caller chose what should send to server,if server side accept it ,it works,if not,caller should make change,not the library.
- if library have to do type conversion in some case,especially a narrowing primitive conversion ,libaray should check (or report) for data loss,who convert who check ,right?

what you think of this idea? 

Thank again for share this awesome project,cheers .

**Comment by ribasco** [comment]
sorry for the late reply.

You have raised some valid points. Initially the pojos were auto-generated by a third party tool where most of the numeric properties you have mentioned have defaulted to int types, so clearly there are still some remaining that needs to be identified and refactored for consistency.

 I will keep this open until I have managed to identify the rest (any help would also be greatly appreciated as I am stuck between projects right now).
