### ISSUE TITLE
Compatibility with GraalVM Native Image

### ISSUE THREAD

**Issue by DarkAtra** [ribasco/async-gamequery-lib#165]
It would be awesome if this lib would provide hints for GraalVM so that users can create native images of their application. E.g.: https://www.graalvm.org/22.1/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file

**Comment by DarkAtra** [comment]
So far it seems like the following runtime reflection hints are enough:

`META-INF/native-image/com.ibasco.agql/async-gamequery-lib/reflect-config.json`:
```
[
  {
    "name": "com.ibasco.agql.core.util.ConnectOptions",
    "allPublicFields": true,
    "allPublicConstructors": true
  },
  {
    "name": "com.ibasco.agql.core.util.FailsafeOptions",
    "allPublicFields": true,
    "allPublicConstructors": true
  },
  {
    "name": "com.ibasco.agql.core.util.GeneralOptions",
    "allPublicFields": true,
    "allPublicConstructors": true
  },
  {
    "name": "com.ibasco.agql.core.util.HttpOptions",
    "allPublicFields": true,
    "allPublicConstructors": true
  },
  {
    "name": "com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions",
    "allPublicFields": true,
    "allPublicConstructors": true
  },
]
```

The above config is required as `Option#create` uses reflection to find the declaring class, `OptionBuilder#<init>` uses `Class#newInstance` and `Option#initialize` loops over all fields declared in each `Option` class to invoke each fields getter.

Netty already supports GraalVM via https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/io.netty

I tested it partially on MacOS (x86_64) and Windows (x86_64) via https://github.com/DarkAtra/v-rising-discord-bot/issues/63. There seems to be an issue on Linux (x86_64) but i'm not sure if it's related to this project or to netty (i'm still investigating).

**Comment by ribasco** [comment]
Thank you for this. I haven't had the chance to test this fully (computer broke down last week). Will provide further feedback once I get things up and running again.

**Comment by DarkAtra** [comment]
Could you release the new version of the lib? :D
