### ISSUE TITLE
GetMatchHistoryBySequenceNum not work

### ISSUE THREAD

**Issue by John-Chan** [ribasco/async-gamequery-lib#20]
because startSeqNum is used to pass match sequence number which is a 64 bit integer,but the constructor of GetMatchHistoryBySequenceNum only accept int32.

**Comment by ribasco** [comment]
Duplicate of #14.

**Comment by ribasco** [comment]
Reference b612971c2abe1ab83bae7d7c9fa8460f09b4e888
