### ISSUE TITLE
[Source Server Query] Encoding issue

### ISSUE THREAD

**Issue by sweepyoface** [ribasco/async-gamequery-lib#23]
I'm having an issue where if the server hostname contains the `│` character (\u2502), `SourceQueryClient.getServerInfo()` returns it as `â??`. Is there a way to specify the encoding used? I'm not sure how to resolve this problem.

**Comment by ribasco** [comment]
you could try and re-encode the returned string e.g:

```
        SourceQueryClient sourceQueryClient = new SourceQueryClient();
        SourceServer serverInfo = sourceQueryClient.getServerInfo(new InetSocketAddress("<ip>", 27015)).get();
        byte[] data = serverInfo.getName().getBytes(ISO_8859_1);
        String encodedStr = new String(data, "UTF-8");
        System.out.println(encodedStr);
```

**Comment by sweepyoface** [comment]
That worked, thanks! Is there a reason why the data is encoded in ISO-8859-1 and not UTF-8?

**Comment by ribasco** [comment]
For `getBytes(ISO_8859_1)`. No particular reason, that was just for the sake of example. You can use UTF-8  in your case.
