### ISSUE TITLE
SteamWebApi connects to http instead of https [fixed in master]

### ISSUE THREAD

**Issue by Daklerid** [ribasco/async-gamequery-lib#28]
All requests to retrieve game info give exceptions. Steam moved the API to https and the 302 status code is not handled correctly. I noticed that this is fixed in master. Could master be released, please?

**Comment by ribasco** [comment]
Related ticket #26

**Comment by ribasco** [comment]
0.1.6 release has been pushed. Should take a few hours to sync with central

**Comment by Daklerid** [comment]
Thank you
