### ISSUE TITLE
Time out while retrieving Player list. 

### ISSUE THREAD

**Issue by DarkScientist** [ribasco/async-gamequery-lib#46]
**Describe the bug**
When trying to retrieve Player list from a Garry's Mod server through the example in the documentation, program returns a timed out. 

**Expected behavior**
It should have returned me a list of SourcePlayer.

Thanks for your help.

**Comment by Keinstah** [comment]
I have the same issue, have you managed to resolved it?

**Comment by ribasco** [comment]
Closing. Feel free to re-open if issues are still present at v1.0
