### ISSUE TITLE
A2S_INFO change

### ISSUE THREAD

**Issue by Mikusch** [ribasco/async-gamequery-lib#50]
The library is currently unusable with the change Valve detailed in a post about 9 months ago:
https://steamcommunity.com/discussions/forum/14/2974028351344359625/

This change is rolling out to more and more games, breaking compatibility of this library.

The updated specification can be found here: https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO

**Comment by Mikusch** [comment]
@ribasco Thanks for noticing the issue.

As of recent updates for various Source 1 games (such as the 9/17/2021 Team Fortress 2 update), fetching server info always leads to a timeout. I have several applications that depend on this library to fetch server info.

Is there a possibility of a fix version being available sometime soon?

**Comment by ribasco** [comment]
> @ribasco Thanks for noticing the issue.

Thanks for bringing this to my attention. 

> Is there a possibility of a fix version being available sometime soon?

I'm already working on it as we speak and decided to push this fix for v0.2.0. Will you be available any time next week for testing?

**Comment by Mikusch** [comment]
> I'm already working on it as we speak and decided to push this fix for v0.2.0. Will you be available any time next week for testing?

Yes, I can help with testing.

**Comment by Mikusch** [comment]
Any updates on this?

**Comment by ribasco** [comment]
> Any updates on this?

Apologies if I haven't responded promptly. Just an update, I ultimately decided to re-write most part of the library and push the changes to [v1.0.0](https://github.com/ribasco/async-gamequery-lib/blob/master/CHANGELOG.md) instead. 

If you are still available for a quick test, the snapshot artifacts ([1.0.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/ibasco/agql/)) are now available at the sonatype repository.

**Comment by ribasco** [comment]
Closing for now. This has been resolved in v1.0.0 release. Feel free to re-open if you encounter any more issues with the release.
