### ISSUE TITLE
Add Server Port to SourceQueryInfoResponse

### ISSUE THREAD

**Issue by DarkAtra** [ribasco/async-gamequery-lib#62]
### Describe the problem you'd like to have solved

I'm trying to retrieve the game port of a server via the getInfo query and then display it in a status message.

### Describe the solution you'd like

It would be great if `edfServerPort` was mapped into the `SourceQueryInfoResponse` instead of discarding it (`SourceQueryInfoDecoder` L96).

**Comment by ribasco** [comment]
Thanks for reporting. I initially thought the game and query ports are always the same. I'll map this to a new field `gamePort`

**Comment by ribasco** [comment]
I have pushed the changes to 1.0.3. You should now be able to retrieve the game port number via `SourceServer#getGamePort()`

**Comment by DarkAtra** [comment]
Thank you! Works as expected.
